# Generated by Django 4.1.9 on 2023-05-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SD', 'Scraping Data'), ('NME', 'Needs Manual Entry'), ('RFR', 'Ready for Review'), ('ES', 'Error Scraping'), ('ET', 'Error Submitting'), ('SB', 'Submitted'), ('AP', 'Approved'), ('DN', 'Denied')], max_length=3)),
                ('name_of_business', models.CharField(max_length=255)),
                ('status_date', models.DateField()),
                ('legal_business_name', models.CharField(max_length=255)),
                ('owners', models.TextField()),
                ('users_cash_advance', models.BooleanField()),
                ('have_cash_advance', models.BooleanField()),
                ('credit_score', models.PositiveIntegerField()),
                ('business_name_match_flag', models.BooleanField()),
            ],
        ),
    ]
